LoginSessionTest/Models/Car.cs
namespace LoginSessionTest.Models
{
    public class Car
    {
        public string Regnr { get; set; }
        public string Model { get; set; }

        public User Driver { get; set; }

        public Car()
        {

        }
        public Car(string regNr, string model)
        {
            Regnr = regNr;
            Model = model;
        }

        public void AddDriver(User user)
        {
            Driver = user;
        }

        public override string ToString()
        {
            return $"Regnr  {Regnr} Model {Model} Drivername {Driver.UserName}";
        }
    }
}

LoginSessionTest/Models/User.cs
namespace LoginSessionTest.Models
{
    public class User
    {
        public int Id { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }

    }
}

LoginSessionTest/Pages/Cars/GetAllCars.cshtml.cs
using LoginSessionTest.Interfaces;
using LoginSessionTest.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace LoginSessionTest.Pages.Cars
{
    public class GetAllCarsModel : PageModel
    {
        private ICarService _carService;
        private IUserService _userService;

        public string UserName { get; set; }

        public List<Car> Cars { get; set; }

        public GetAllCarsModel(ICarService carService, IUserService userservice)
        {
            _carService = carService;
            _userService = userservice;
        }

        public IActionResult OnGet()
        {
            UserName = HttpContext.Session.GetString("UserName");
            if (UserName == null)
            {
                return RedirectToPage("/Users/Login");
            }
            Cars = _carService.GetAllCars();
            return Page();
        }

        public IActionResult OnPostAddDriver(string carRegNr)
        {
            UserName = HttpContext.Session.GetString("UserName");
            if (UserName == null)
            {
                return RedirectToPage("/Users/Login");
            }
            User currentUser = _userService.GetUserByUserName(UserName);

            Car aCar = _carService.GetCarByRegnr(carRegNr);
            aCar.AddDriver(currentUser);
            return Page();
        }
    }
}

LoginSessionTest/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace LoginSessionTest.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

LoginSessionTest/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace LoginSessionTest.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public string UserName { get; set; }
        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public IActionResult OnGet()
        {
            UserName = HttpContext.Session.GetString("UserName");
            if (UserName == null)
            {
                return RedirectToPage("Users/Login");
            }
            else
                return Page();

        }
    }
}

LoginSessionTest/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace LoginSessionTest.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

LoginSessionTest/Pages/Users/GetAllUsers.cshtml.cs
using LoginSessionTest.Interfaces;
using LoginSessionTest.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace LoginSessionTest.Pages.Users
{
    public class GetAllUsersModel : PageModel
    {
        private IUserService _userService;

        public string UserName { get; set; }
        public List<User> Users { get; set; }
        public GetAllUsersModel(IUserService userService)
        {
            _userService = userService;
        }
        public IActionResult OnGet()
        {
            UserName = HttpContext.Session.GetString("UserName");
            if (UserName == null)
            {
                return RedirectToPage("/Users/Login");
            }
            Users = _userService.GetAllUsers();
            return Page();
        }
    }
}

LoginSessionTest/Pages/Users/Login.cshtml.cs
using LoginSessionTest.Interfaces;
using LoginSessionTest.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace LoginSessionTest.Pages.Users
{
    public class LoginModel : PageModel
    {
        [BindProperty] public string UserName { get; set; }
        [BindProperty] public string PassWord { get; set; }

        public string Message { get; set; }

        private IUserService _userService;
        public LoginModel(IUserService userservice)
        {
            _userService = userservice;
        }

        public void OnGet()
        {
        }

        public void OnGetLogout()
        {
            HttpContext.Session.Remove("UserName");
        }

        public IActionResult OnPost()
        {
            User loginUser = _userService.VerifyUser(UserName, PassWord);
            if (loginUser != null)
            {
               
                HttpContext.Session.SetString("UserName", loginUser.UserName);
                return RedirectToPage("/Welcome");
            }
            else
            {
                Message = "Invalid username or password";
                UserName = "";
                PassWord = "";
                return Page();
            }

        }
    }
}

LoginSessionTest/Pages/Welcome.cshtml.cs
using LoginSessionTest.Interfaces;
using LoginSessionTest.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace LoginSessionTest.Pages
{
    public class WelcomeModel : PageModel
    {
        private IUserService _userService; 
        public string UserName { get; set; }

        public User CurrentUser { get; set; }

        public WelcomeModel(IUserService userService)
        {
            _userService = userService;
        }
        public IActionResult OnGet()
        {
            UserName = HttpContext.Session.GetString("UserName");
            if (UserName== null)
            {
                return RedirectToPage("Users/Login");
            }
            else
            {
                CurrentUser = _userService.GetUserByUserName(UserName); 
            }
            return Page();
        }
    }
}

LoginSessionTest/Pages/Cars/GetAllCars.cshtml
@page
@using LoginSessionTest.Models
@model LoginSessionTest.Pages.Cars.GetAllCarsModel
@{
}
<h4>Du er logget in som @Model.UserName</h4>
<table class="table">
    <thead>
        <tr>
            <th>
                RegNr
            </th>
            <th>
                Model
            </th>
            <th>
                Action
            </th>
        </tr>
    </thead>
    <tbody>
        @if (Model.Cars.Count() != 0)
        {
            @foreach (Car item in Model.Cars)
            {
                <tr>
                    <td>
                        @item.Regnr
                    </td>
                    <td>
                        @item.Model
                    </td>

                    <td>
                        <p>
                            <form method="post">
                                <input type="submit" value="Add driver" asp-page-handler="AddDriver" asp-route-carRegNr="@item.Regnr" />
                            </form>
                        </p>
                    </td>
                </tr>
            }
        }
    </tbody>
</table>

LoginSessionTest/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome @Model.UserName</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

LoginSessionTest/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LoginSessionTest</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/LoginSessionTest.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">LoginSessionTest</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Welcome">Welcome</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Users/GetAllUsers">All users</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Users/Login">Login</a>
                        </li>
                    </ul>
                </div>   
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - LoginSessionTest - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

LoginSessionTest/Pages/Users/CreateUser.cshtml
@page
@model LoginSessionTest.Pages.Users.CreateUserModel
@{
    ViewData["Title"] = "Create new user";
}
<h1>Register a new user</h1>
<div>
    <h2>Opret ny bruger:</h2>
    <form method="post">
        <div>
            <label asp-for="@Model.NewUser.Id" class="control-label"></label>
            <input asp-for="@Model.NewUser.Id" class="form-control" />
        </div>
        <div>
            <label asp-for="@Model.NewUser.UserName" class="control-label"></label>
            <input asp-for="@Model.NewUser.UserName" class="form-control" />
        </div>

        <div class="form-group">
            <label asp-for="@Model.NewUser.Password" class="control-label"></label>
            <input asp-for="@Model.NewUser.Password" class="form-control" />
        </div>
        <div class="form-group">
            <label asp-for="@Model.NewUser.Email" class="control-label"></label>
            <input asp-for="@Model.NewUser.Email" class="form-control" />
        </div>
        <div class="form-group">
            <input type="submit" value="Tilføj bruger" class="btn btn-outline-success" />
        </div>
    </form>
</div>

LoginSessionTest/Pages/Users/GetAllUsers.cshtml
@page
@model LoginSessionTest.Pages.Users.GetAllUsersModel
@{
}
<h4>Du er logget in som @Model.UserName</h4>
<table class="table">
    <thead>
        <tr>
            <th>
                Id
            </th>
            <th>
                UserName
            </th>
            <th>
                Email
            </th>
        </tr>
    </thead>
    <tbody>
        @if (Model.Users.Count() != 0)
        {
            @foreach (var item in Model.Users)
            {
                <tr>
                    <td>
                        @item.Id
                    </td>
                    <td>
                        @item.UserName
                    </td>
                    <td>
                        @item.Email
                    </td>
                    <td>
                        <p>
                            <a asp-page="/Users/DeleteUser" asp-route-userId="@item.Id">Delete</a>
                        </p>
                    </td>
                </tr>
            }
        }
    </tbody>
</table>

LoginSessionTest/Pages/Users/Login.cshtml
@page
@model LoginModel
@{
}

<h3>Login form</h3>
@Model.Message
<form method="post">
    <table>
        <tr>
            <td>UserName  (Poul eller Charlotte)</td>
            <td><Input type="text" asp-for="@Model.UserName" /></td>
        </tr>
        <tr>
            <td>Password (123)</td>
            <td><Input type="password" asp-for="@Model.PassWord" /></td>
        </tr>
        <tr>
            <td>&nbsp</td>
            <td><Input type="submit" value="Login" /></td>
        </tr>
    </table>
    <a asp-page="CreateUser">Create a new user</a>
</form>

LoginSessionTest/Pages/Welcome.cshtml
@page
@model LoginSessionTest.Pages.WelcomeModel
@{
}

<h3>Welcome to @Model.UserName</h3>

<a asp-page="/users/LogIn" asp-page-handler="Logout">Logout</a>

<h2>Bruger har id   @Model.CurrentUser.Id  og email  @Model.CurrentUser.Email </h2>